import mongoose, { Schema } from "mongoose";

const CompanySettingsSchema = new Schema(
  {
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      ref: "Company",
    },
    currentCurrency: { type: String, required: true },
    allowMultiCurrency: { type: Boolean, default: false },
    currencySymbol: { type: String, required: true },
    decimalPlaces: { type: Number, default: 2 },
    multiplePriceLevels: { type: Boolean, default: false },
    enableMultipleDiscount: { type: Boolean, default: false },
    enableGeography: { type: Boolean, default: false },
    enableNegativeStockEntries: { type: Boolean, default: false },
    enableImageCompression: { type: Boolean, default: false },
    showPackagingDetails: { type: Boolean, default: false },
    allowSalesPersonInvoiceFilter: { type: Boolean, default: false },
    showSalePrice: { type: Boolean, default: true },
    showCostPrice: { type: Boolean, default: true },
    showRetailPrice: { type: Boolean, default: true },
    salesQuotationComments: { type: String, default: "" },
    salesInvoiceComments: { type: String, default: "" },
    posInvoiceComments: { type: String, default: "" },
    showBatchNo: { type: Boolean, default: false },
    showBatchExpiry: { type: Boolean, default: false },
    showBranchesZeroQuantity: { type: Boolean, default: false },
    autoBatchNo: { type: Boolean, default: false },
    finYearStart: {
      type: String,
      required: true,
      enum: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ],
    },
    enableNarration: { type: Boolean, default: false },
    reduceCostOnPurchaseDiscount: { type: Boolean, default: false },
    reduceSaleOnSaleDiscount: { type: Boolean, default: false },
    allowTransactionsPreviousYear: { type: Boolean, default: false },
    showOutstandingBalanceInward: { type: Boolean, default: false },
    showOutstandingBalanceOutward: { type: Boolean, default: false },
    showTransactionNo: { type: Boolean, default: false },
    enableSms: { type: Boolean, default: false },
    enableCopyCommentsInward: { type: Boolean, default: false },
    enableCopyCommentsOutward: { type: Boolean, default: false },
    enableUndepositedFundsForwarding: { type: Boolean, default: false },
    enableWHTaxSales: { type: Boolean, default: false },
    enableWHTaxPurchases: { type: Boolean, default: false },
    discountType: {
      type: String,
      enum: ["PERCENT", "AMOUNT", "QT"],
      default: "PERCENT",
    },
    defaultPostCustomer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customer",
    },
    allowPosDiscount: { type: Boolean, default: false },
    allowPosPriceChange: { type: Boolean, default: false },
    allowPosRemoveProductAfterScanning: { type: Boolean, default: false },
    allowOverallPosDiscountAtTotal: { type: Boolean, default: false },
    manuallyManageEOD: { type: Boolean, default: false },
    enableForPos: { type: Boolean, default: false },
    enableCreditSales: { type: Boolean, default: false },
    enableConsignmentTracking: { type: Boolean, default: false },
    enableBranches: { type: Boolean, default: false },
    shareStockForBranches: { type: Boolean, default: false },
    branchWiseCustomerFilter: { type: Boolean, default: false },
  },
  { timestamps: true }
);

export const CompanySettings = mongoose.model(
  "CompanySettings",
  CompanySettingsSchema
);
